spring.application.name=demo

# Google OAuth2 Settings (Use environment variables for sensitive info)
spring.security.oauth2.client.registration.google.client-id=33619914845-k3elr3n3euh79imcrm63lpea240rfjga.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5173/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


# DataSource configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/users
spring.datasource.username=postgres
spring.datasource.password=nabeel
spring.jpa.hibernate.ddl-auto=update

server.port=8080